name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 8.2
            laravel: '^9.0'
            testbench: '^7.0'
          - php: 8.2
            laravel: '^10.0'
            testbench: '^8.0'
          - php: 8.2
            laravel: '^11.0'
            testbench: '^9.0'
          - php: 8.3
            laravel: '^9.0'
            testbench: '^7.0'
          - php: 8.3
            laravel: '^10.0'
            testbench: '^8.0'
          - php: 8.3
            laravel: '^11.0'
            testbench: '^9.0'
          - php: 8.3
            laravel: '^12.0'
            testbench: '^10.0'
          - php: 8.4
            laravel: '^11.0'
            testbench: '^9.0'
          - php: 8.4
            laravel: '^12.0'
            testbench: '^10.0'

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
        coverage: xdebug

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php }}-

    - name: Install dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
        composer install --prefer-dist --no-interaction --no-progress

    - name: Run test suite
      run: composer test

  docker-test:
    runs-on: ubuntu-latest
    name: Docker Tests
    
    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t laravel-commonmark-blog .

    - name: Run tests in Docker
      run: docker run --rm laravel-commonmark-blog

    - name: Run tests with coverage in Docker
      run: docker run --rm laravel-commonmark-blog composer test-coverage